In [55]:
# import json

# package = {}
# with open("../package.json") as f:
#     package = json.load(f)

# with open("../package-lock.json") as f:
#     data = json.load(f)
#     data["devDependencies"] = {
#         each: "^" + data["packages"]["node_modules/" + each]["version"]
#         for each in data["packages"][""]["devDependencies"]
#     }

# with open("../package.json", "w") as f:
#     json.dump(package, f, indent=4)

In [56]:
from typing import List


def reorder_array(arr: List[str], start_value: str) -> List[str]:
    try:
        start_index = arr.index(start_value)
    except ValueError:
        return arr  # start_value not found, return as is

    return arr[start_index:] + arr[:start_index]

In [57]:
rahu_kalamPortionIndex = [8, 2, 7, 5, 6, 4, 3]

In [58]:
dayLords = ["Sun", "Moon", "Mars", "Mercury", "Jupiter", "Venus", "Saturn"]

grahaSequence = []
data = []
for i in range(7):
    graha_sequence = reorder_array(dayLords, dayLords[i])
    grahaSequence.append(graha_sequence)
    data.append(
        {
            "Gulika": graha_sequence.index("Saturn"),
            "Kaala": graha_sequence.index("Sun"),
            "Mrityu": graha_sequence.index("Mars"),
            "Yamaghantaka": graha_sequence.index("Jupiter"),
            "Ardhaprahara": graha_sequence.index("Mercury"),
            "RahuKaal": rahu_kalamPortionIndex[i],
        }
    )

import pandas as pd

pd.DataFrame(grahaSequence)

         0        1        2        3        4        5        6
0      Sun     Moon     Mars  Mercury  Jupiter    Venus   Saturn
1     Moon     Mars  Mercury  Jupiter    Venus   Saturn      Sun
2     Mars  Mercury  Jupiter    Venus   Saturn      Sun     Moon
3  Mercury  Jupiter    Venus   Saturn      Sun     Moon     Mars
4  Jupiter    Venus   Saturn      Sun     Moon     Mars  Mercury
5    Venus   Saturn      Sun     Moon     Mars  Mercury  Jupiter
6   Saturn      Sun     Moon     Mars  Mercury  Jupiter    Venus

In [59]:
pd.DataFrame(data)

   Gulika  Kaala  Mrityu  Yamaghantaka  Ardhaprahara  RahuKaal
0       6      0       2             4             3         8
1       5      6       1             3             2         2
2       4      5       0             2             1         7
3       3      4       6             1             0         5
4       2      3       5             0             6         6
5       1      2       4             6             5         4
6       0      1       3             5             4         3